server:
  port: 8080
#  servlet:
#    context-path: /api

# 日志
logging:
  level:
    com.scau.ebmarket.controller: debug
#    springfox.documentation.schema.property.CachingModelPropertiesProvider: error

# dataSource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elevmanage?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      location: G:/Code/elevmanage/uploads/
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

schedules:
  runBatch:  0 0 12 * * ?

# mp配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.scau.zwp.elevmanage.entity, com.scau.zwp.elevmanage.vo
  global-config:
    db-config:
      # 主键生成策略（AUTO务必在数据库表中设置自增字段）
      id-type: AUTO
      # 逻辑删除字段名
      logic-delete-field: isDeleted
      # 逻辑删除字面值：未删除为0
      logic-not-delete-value: 0
      # 逻辑删除字面值：删除为1
      logic-delete-value: 1
      # 表名添加前缀
      # table-prefix: em_
    banner: off
    # 在控制台开启mybatis日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#springfox:
#  documentation:
#    swagger-ui:
#      enabled: on

# Knife4j配置
knife4j:
  # 是否开启增强模式
  enable: true
